export { default as GraficaPie } from "./GraficaPie.vue";
export { default as GraficaBar } from "./GraficaBar.vue";
export { default as Cobertura } from "./Cobertura.vue";
export { default as Implementaciones } from "./Implementaciones.vue";
export { default as Carbono } from "./Carbono.vue";
export { default as Biodiversidad } from "./Biodiversidad.vue";
export { default as DownloadImageBtn } from "./DownloadImageBtn.vue";
export { default as ParticipantesGenero } from "./ParticipantesGenero.vue";
export { default as ParticipantesOtros } from "./ParticipantesOtros.vue";
