export { default as Cobertura } from "./Cobertura.vue";
export { default as Implementaciones } from "./Implementaciones.vue";
export { default as Carbono } from "./Carbono.vue";
export { default as Biodiversidad } from "./Biodiversidad.vue";
export { default as Participantes } from "./Participantes.vue";
export { default as QuantityText } from "./QuantityText.vue";
export { default as Metas } from "./Metas.vue";
export { default as Contribuciones } from "./Contribuciones.vue";
export { default as Aliados } from "./Aliados.vue";
